export const names = {
  humanMale: [
    "Anlow",
    "Arando",
    "Bram",
    "Cale",
    "Dalkon",
    "Daylen",
    "Dodd",
    "Dungarth",
    "Dyrk",
    "Eandro",
    "Falken",
    "Feck",
    "Fenton",
    "Gryphero",
    "Hagar",
    "Jeras",
    "Krynt",
    "Lavant",
    "Leyten",
    "Madian",
    "Malfier",
    "Markus",
    "Meklan",
    "Namen",
    "Navaren",
    "Nerle",
    "Nilus",
    "Ningyan",
    "Norris",
    "Quentin",
    "Semil",
    "Sevenson",
    "Steveren",
    "Talfen",
    "Tamond",
    "Taran",
    "Tavon",
    "Tegan",
    "Vanan",
    "Vincent"
  ],
  humanFemale: [
    "Azura",
    "Brey",
    "Hallan",
    "Kasaki",
    "Lorelei",
    "Mirabel",
    "Pharana",
    "Remora",
    "Rosalyn",
    "Sachil",
    "Saidi",
    "Tanika",
    "Tura",
    "Tylsa",
    "Vencia",
    "Xandrilla"
  ],
  humanLastName: [
    "Arkalis",
    "Armanci",
    "Bilger",
    "Blackstrand",
    "Brightwater",
    "Carnavon",
    "Caskajaro",
    "Coldshore",
    "Coyle",
    "Cresthill",
    "Cuttlescar",
    "Daargen",
    "Dalicarlia",
    "Danamark",
    "Donoghan",
    "Drumwind",
    "Dunhall",
    "Ereghast",
    "Falck",
    "Fallenbridge",
    "Faringray",
    "Fletcher",
    "Fryft",
    "Goldrudder",
    "Grantham",
    "Graylock",
    "Gullscream",
    "Hindergrass",
    "Iscalon",
    "Kreel",
    "Kroft",
    "Lamoth",
    "Leerstrom",
    "Lynchfield",
    "Moonridge",
    "Netheridge",
    "Oakenheart",
    "Pyncion",
    "Ratley",
    "Redraven",
    "Revenmar",
    "Roxley",
    "Sell",
    "Seratolva",
    "Shanks",
    "Shattermast",
    "Shaulfer",
    "Silvergraft",
    "Stavenger",
    "Stormchapel",
    "Strong",
    "Swiller",
    "Talandro ",
    "Targana",
    "Towerfall",
    "Umbermoor",
    "Van Devries",
    "Van Gandt",
    "Van Hyden",
    "Varcona",
    "Varzand",
    "Voortham",
    "Vrye",
    "Webb",
    "Welfer",
    "Wilxes",
    "Wintermere",
    "Wygarthe",
    "Zatchet",
    "Zethergyll"
  ],
  dwarfMale: [
    "Agaro",
    "Arnan",
    "Auxlan",
    "Avamir",
    "Baelnar",
    "Balfam",
    "Bariken",
    "Borkûl",
    "Darkûl",
    "Dolmen",
    "Dyrnar",
    "Erag",
    "Ezegan",
    "Ferrek",
    "Garmûl",
    "Glint",
    "Ghorvas",
    "Grimmalk",
    "Haeltar",
    "Halagmar",
    "Halzar",
    "Hlant",
    "Korlag",
    "Krag",
    "Krim",
    "Kurman",
    "Lurtrum",
    "Malagar",
    "Mardam",
    "Maulnar",
    "Melgar",
    "Morak",
    "Orobok",
    "Rogath",
    "Roken",
    "Rozag",
    "Sabakzar",
    "Sharak",
    "Smethykk",
    "Swargar",
    "Thorbalt",
    "Thorin",
    "Tredigar",
    "Vabûl",
    "Vistrum",
    "Wolvar"
  ],
  dwarfFemale: [
    "Beyla",
    "Fenryl",
    "Grenenzel",
    "Krystolari",
    "Lokara",
    "Lurka",
    "Marnia",
    "Praxana",
    "Rokel",
    "Roksana",
    "Thurlfara",
    "Vauldra",
    "Veklani",
    "Vronwe",
    "Zebel"
  ],
  dwarfLastName: [
    "Ambershard",
    "Barrelhelm",
    "Copperhearth",
    "Deepmiddens",
    "Drakantal",
    "Evermead",
    "Garkalan",
    "Grimtor",
    "Hackshield",
    "Irongull",
    "Markolak",
    "Ramcrown",
    "Rockharvest",
    "Silvertarn",
    "Skandalor",
    "Zarkanan"
  ],
  elfMale: [
    "Alarcion",
    "Alathar",
    "Ariandar",
    "Arromar",
    "Borel",
    "Bvachan",
    "Carydion",
    "Elgoth",
    "Farlien",
    "Ferel",
    "Gaerlan",
    "Iafalior",
    "Kaelthorn",
    "Laethan",
    "Leliar",
    "Leodor",
    "Lorak",
    "Lorifir",
    "Morian",
    "Oleran",
    "Rylef",
    "Savian",
    "Seylas",
    "Tevior",
    "Veyas"
  ],
  elfFemale: [
    "Aryllan",
    "Atalya",
    "Ayrthwil",
    "Irva",
    "Lyfalia",
    "Ronefel",
    "Thirya",
    "Velene",
    "Venefiq",
    "Zereni"
  ],
  elfLastName: [
    "Autumnloft",
    "Balefrost",
    "Briarfell",
    "Evenwind",
    "Graytrails",
    "Mooncairn",
    "Riverwall",
    "Stormwolf",
    "Summergale",
    "Sunshadow",
    "Woodenhawk"
  ],
  otherMale: [
    "Aialon",
    "Elarahal",
    "Jiardem",
    "Laern",
    "Lelyrian",
    "Lephyrr",
    "Loray",
    "Sayadar",
    "Talonien",
    "Vaerlan",
    "Xoneras",
    "Zaquivir",
    "Arthan",
    "Carvin",
    "Corby",
    "Cullen",
    "Egen",
    "Ernest",
    "Gedi",
    "Heron",
    "Jeryl",
    "Keffen",
    "Kylem",
    "Kynt",
    "Leskyn",
    "Neff",
    "Orne",
    "Quarrel",
    "Rabbit",
    "Rilkin",
    "Snakebait",
    "Tarfen",
    "Titch",
    "Tuck",
    "Whim",
    "Ankhus",
    "Arkadi",
    "Armarius",
    "Armillius",
    "Archidius",
    "Balmoloch",
    "Calderax",
    "Cavian",
    "Cenereth",
    "Chorum",
    "Corynax",
    "Dacian",
    "Daelius",
    "Damaceus",
    "Decimeth",
    "Demedor",
    "Demerian",
    "Dynachus",
    "Grassus",
    "Halius",
    "Heleph",
    "Incirion",
    "Kalaradian",
    "Kamien",
    "Kazimir",
    "Kzandro",
    "Machem",
    "Maetheus",
    "Malfias",
    "Marchion",
    "Menerus",
    "Namazeus",
    "Nensis",
    "Prismeus",
    "Pyranikus",
    "Razortail",
    "Sejanus",
    "Severian",
    "Suffer",
    "Syken",
    "Tarkus",
    "Vaius",
    "Xerek",
    "Zeth",
    "Zevon"
  ],
  otherFemale: [
    "Allyria",
    "Ayrdra",
    "Deneth",
    "Elseone",
    "Etherea",
    "Istiria",
    "Karanwyn",
    "Lieryn",
    "Ravel",
    "Sinariel",
    "Sydri",
    "Taris",
    "Turue",
    "Vacquiel",
    "Valendra",
    "Caliope",
    "Emily",
    "Piper",
    "Rixi",
    "Sabretha",
    "Teg",
    "Tilly",
    "Toira",
    "Vexia",
    "Vil",
    "Vzani",
    "Zanthe",
    "Ziza",
    "Affyria",
    "Cataclysmia",
    "Domitia",
    "Dorethau",
    "Excellence",
    "Hacari",
    "Iritra",
    "Lachira",
    "Levatra",
    "Mecretia",
    "Milvia",
    "Nericia",
    "Precious",
    "Rain",
    "Samantia",
    "Sunshine",
    "Tenerife",
    "Traya",
    "Velavia",
    "Zaidi",
    "Zethaya"
  ],
  otherLastName: [
    "Amarzian",
    "Carnago",
    "Domarien",
    "Iscitan",
    "Meluzan",
    "Menetrian",
    "Paradas",
    "Romazi",
    "Sarzan",
    "Serechor",
    "Shadowhorn",
    "Szereban",
    "Torzalan",
    "Trelenus",
    "Trevethor",
    "Tryphon",
    "Vadu",
    "Vrago",
    "Angler",
    "Battlestone",
    "Blackwater",
    "Daggersharp",
    "Deepstrider",
    "Hollowpot",
    "Puddle",
    "Raftmite",
    "Skiprock",
    "Silverfin",
    "Tanglestrand",
    "Tricker",
    "Willowrush",
    "Yellowcrane",
    "Lantherval",
    "Lorhalien",
    "Maldranthe",
    "Shalbarain",
    "Sirothian",
    "Starfeon",
    "Zolerii"
  ],
  innShipTavern: [
    "Advantage",
    "Arazandro’s Bluff",
    "Archon’s Hammer",
    "Arkhor’s Secret",
    "Arrowhead",
    "Asha-Naga",
    "Astaryntha",
    "Aurora",
    "Autumn Song",
    "Avarice",
    "Axe of Thard",
    "Bane’s Breath",
    "Barracuda",
    "Beholder",
    "Bharzim’s Victory",
    "Bhez-Rizma",
    "Black Bow",
    "Black Gauntlet",
    "Black Trident",
    "Blackhelm’s Legacy",
    "Blademark",
    "Bloodmonger",
    "Breyten’s Thrill",
    "Broken Keel",
    "Calomaar’s Edge",
    "Chethel’s Ghost",
    "Color Spray",
    "Coral Rose",
    "Corellon’s Arrow",
    "Crescent Moon",
    "Crimson Knife",
    "Crystal Tear",
    "Curse of Thuban",
    "Damilor",
    "Dancing Sword",
    "Daraj-Vzan",
    "Dark Queen’s Voice",
    "Deep Heathen",
    "Demonrudder",
    "Demonskull",
    "DesperateSorceress",
    "Devil’s Fork",
    "Devious",
    "Dire Gar",
    "Djinni’s Wish",
    "Dominant",
    "Dragon’s Crown",
    "Dragon’s Glory",
    "Dragonhawk",
    "Dragonroar",
    "Dream of Melora",
    "Dryad’s Fury",
    "Ebon Moon",
    "Emerald Eye",
    "Evader",
    "Expeditious",
    "Falling Star",
    "Fang of Tezmyr",
    "Farak-Changal",
    "Fate’s Blessing",
    "Fearsome",
    "Feral Knave",
    "Fireball",
    "Floating Cask",
    "Flying Eel",
    "Frastain’s Bottle",
    "Frostwind",
    "Gem of Malfier",
    "Ghorok’s Grail",
    "Ghorzaar’s Bane",
    "Golden Coin",
    "Golden Libram",
    "Goldraker",
    "Good Fortune",
    "Graethan",
    "Greedy Drake",
    "Griffonwing",
    "Grim Gale",
    "Grimbol’s Cutlass",
    "Hammer of Kavath",
    "Hammergust",
    "Hareth’s Barrel",
    "Harpy’s Lure",
    "Heart of Avandra",
    "Heartless",
    "Hellstrike",
    "Hjeltia",
    "Iron Maiden",
    "Iron Trumpet",
    "Jarak’s Grasp",
    "Javelin",
    "Jewel of Irthos",
    "Kalisa Tano",
    "Kara-Vaji",
    "Karthang’s Plunder",
    "Kasha’s Wake",
    "Kaveth’s Whisper",
    "Kegstaff",
    "Kerle’s Drum",
    "Koalinthas",
    "Kral-Tajir",
    "Krimilvin’s Charm",
    "Lady Rose",
    "Lantheon",
    "Leering Skull",
    "Light of Pelor",
    "Listless",
    "Locathah",
    "Lonely Witch",
    "Lucky Scrag",
    "Maal-Destir",
    "Mad Hag",
    "Maelstrom",
    "Mar-Turang",
    "Melora’s Favor",
    "Menacer",
    "Mirasandra",
    "Mistreaver",
    "Moonriser",
    "Moonshadow",
    "Moonwatcher",
    "Morak’s Boat",
    "Morkoth",
    "Myrska’s Revenge",
    "Nbod’s Haul",
    "Nightmare",
    "Oaken Ranger",
    "Pearl of Fire",
    "Phantom Shark",
    "Piranha",
    "Prallmar’s Shadow",
    "Prince of Lies",
    "Prosperous",
    "Quickstrike",
    "Rangoth",
    "Rat’s Nest",
    "Ravager",
    "Raven’s Gamble",
    "Reckoner",
    "Redemption",
    "Redfeather",
    "Remorseless",
    "Retribution",
    "Risen Ghost",
    "Riventide",
    "Roc’s Talon",
    "Rotten Apple",
    "Rune of Halendros",
    "Rusted Cutlass",
    "Saerthzal",
    "Sahandrian’s Quarrel",
    "Sana-Losi",
    "Sanaj-Rakal",
    "Satyr",
    "Savage Swan",
    "Scarlet Dagger",
    "Scepter Queen",
    "Scimitar",
    "Scorpion",
    "Screaming Gull",
    "Sea Bear",
    "Sea Haunt",
    "Sea Howler",
    "Sea Skulk",
    "Second Chance",
    "Sehanine’s Fool",
    "Shadow Mask",
    "Shalastar",
    "Shara-Vaja",
    "Shard of Night",
    "Shensari",
    "Shevaya’s Honor",
    "Shield of Khahar",
    "Shining Flute",
    "Shoal Courser",
    "Shrike",
    "Silver Chalice",
    "Silverfin",
    "Siren’s Kiss",
    "Skandalor",
    "Skiprock",
    "Skulldark’s Ire",
    "Slippery Trickster",
    "Soaring Manta",
    "Song of Elyndri",
    "Starchaser",
    "Stardancer",
    "Stingray",
    "Storm Maven",
    "Storm’s Eye",
    "Stormcrow",
    "Summer Rain",
    "Sundowner",
    "Tamarion’s Grudge",
    "Tanishar’s Fate",
    "Thelandira",
    "Thog’s Maul",
    "Thunderchaser",
    "Timber Serpent",
    "Tirah",
    "Triton",
    "Trystan’s Delight",
    "Tuersyl’s Fist",
    "Turathi Flame",
    "Vaazrus",
    "Varalan’s Dweomer",
    "Ven’r",
    "Vendetta",
    "Vicious",
    "Vortex",
    "Vostarika",
    "Waterblade",
    "Wavecarver",
    "Wavecrusher",
    "Werewolf",
    "Whirling Glyph",
    "White Feather",
    "White Hart",
    "Wildwyrm",
    "Will-o’-wisp",
    "Windstriker",
    "Wolfshark",
    "Wooden Stake",
    "Wraithwind",
    "Wyvern’s Sting",
    "Yisek’s Ride",
    "Zaetchan’s Privilege",
    "Zaetra",
    "Zarkanan",
    "Zhal-Vazir",
  ]
};
